version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: aws-sdk
    versions:
    - 2.834.0
    - 2.835.0
    - 2.836.0
    - 2.837.0
    - 2.838.0
    - 2.839.0
    - 2.840.0
    - 2.841.0
    - 2.842.0
    - 2.843.0
    - 2.844.0
    - 2.845.0
    - 2.846.0
    - 2.847.0
    - 2.848.0
    - 2.849.0
    - 2.850.0
    - 2.851.0
    - 2.852.0
    - 2.853.0
    - 2.854.0
    - 2.855.0
    - 2.856.0
    - 2.857.0
    - 2.858.0
    - 2.859.0
    - 2.860.0
    - 2.861.0
    - 2.862.0
    - 2.863.0
    - 2.864.0
    - 2.865.0
    - 2.866.0
    - 2.867.0
    - 2.868.0
    - 2.869.0
    - 2.870.0
    - 2.871.0
    - 2.872.0
    - 2.873.0
    - 2.874.0
    - 2.875.0
    - 2.876.0
    - 2.877.0
    - 2.878.0
    - 2.879.0
    - 2.880.0
    - 2.881.0
    - 2.882.0
    - 2.883.0
    - 2.884.0
    - 2.885.0
    - 2.886.0
    - 2.887.0
    - 2.888.0
    - 2.889.0
    - 2.890.0
    - 2.891.0
    - 2.892.0
    - 2.893.0
    - 2.894.0
    - 2.895.0
  - dependency-name: redis
    versions:
    - 3.0.2
    - 3.1.0
    - 3.1.1
  - dependency-name: saucelabs
    versions:
    - 4.6.5
    - 4.6.6
    - 4.6.7
    - 4.6.8
    - 4.7.0
    - 4.7.1
    - 4.7.2
    - 4.7.3
  - dependency-name: apollo-server-core
    versions:
    - 2.19.2
    - 2.20.0
    - 2.21.0
    - 2.21.1
    - 2.21.2
    - 2.22.2
  - dependency-name: "@google-cloud/storage"
    versions:
    - 5.7.3
    - 5.7.4
    - 5.8.0
    - 5.8.1
    - 5.8.2
    - 5.8.3
  - dependency-name: timezonecomplete
    versions:
    - 5.11.2
    - 5.11.4
    - 5.11.5
    - 5.12.0
    - 5.12.1
    - 5.12.2
  - dependency-name: envalid
    versions:
    - 6.0.2
    - 7.0.0
  - dependency-name: knex
    versions:
    - 0.21.16
    - 0.21.17
    - 0.21.18
    - 0.21.19
    - 0.95.0
    - 0.95.1
    - 0.95.2
    - 0.95.3
  - dependency-name: google-libphonenumber
    versions:
    - 3.2.16
    - 3.2.17
    - 3.2.18
  - dependency-name: webpack
    versions:
    - 4.46.0
  - dependency-name: wait-on
    versions:
    - 5.2.1
    - 5.2.2
  - dependency-name: hot-shots
    versions:
    - 8.3.0
  - dependency-name: nodemailer
    versions:
    - 6.4.17
    - 6.4.18
    - 6.5.0
  - dependency-name: yup
    versions:
    - 0.32.8
  - dependency-name: graphql-tools
    versions:
    - 7.0.2
    - 7.0.3
  - dependency-name: json2csv
    versions:
    - 5.0.5
  - dependency-name: moment-timezone
    versions:
    - 0.5.32
  - dependency-name: pg
    versions:
    - 8.5.1
  - dependency-name: twilio
    versions:
    - 3.51.0
  - dependency-name: react
    versions:
    - 15.7.0
    - 17.0.1
  - dependency-name: winston-mongodb
    versions:
    - 5.0.5
    - 5.0.6
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: express-winston
    versions:
    - 4.0.5
  - dependency-name: mockdate
    versions:
    - 3.0.2
    - 3.0.3
    - 3.0.4
  - dependency-name: react-test-renderer
    versions:
    - 16.13.1
    - 17.0.1
  - dependency-name: react-dom
    versions:
    - 16.13.1
  - dependency-name: handlebars
    versions:
    - 4.7.6
