version: 2

jobs:
  build_image:
    docker:
      - image: circleci/node:10.16.0

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Configure GCR access
          command: |
            echo ${GOOGLE_AUTH} > ${HOME}/gcp-key.json
            sudo /opt/google-cloud-sdk/bin/gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
            sudo /opt/google-cloud-sdk/bin/gcloud --quiet config set project ${GCP_PROJECT}

      - run:
          name: Publish Docker image
          command: |
            docker build --rm=false -t gcr.io/spoke-rewired/spoke:$CIRCLE_SHA1 .
            docker tag gcr.io/spoke-rewired/spoke:$CIRCLE_SHA1 gcr.io/spoke-rewired/spoke:latest
            sudo /opt/google-cloud-sdk/bin/gcloud docker -- gcr.io/spoke-rewired/spoke:$CIRCLE_SHA1
            sudo /opt/google-cloud-sdk/bin/gcloud docker -- gcr.io/spoke-rewired/spoke:latest

workflows:
  version: 2

  build_and_push:
    jobs:
      - build_image:
          context: gcp-spoke
          filters:
            branches:
              only: ci/publish-docker-image
